### ISSUE TITLE
Team page not rendering when It's accesed directly by url

### ISSUE THREAD

**Issue by andresgz** [Neocratia/website#8]
If I put in the address bar the following url:
https://www.neocratia.org/team

The page content is not loading.

I get this:
![image](https://user-images.githubusercontent.com/1609644/36937251-7f47eada-1ede-11e8-81f8-704e06d721c3.png)

**Comment by caroso1222** [comment]
I think this issue is related to the web server configuration. You can properly access the page by hitting this URL: https://www.neocratia.org/team/index.html, so it seems like Nginx is not automatically serving the `index.html` file from subfolders.

I tried the following things to reproduce this error on my end, but none of them did the trick. In all of them I was always able to successfully  hit `/team` directly and get the appropriate content:

1. Serve with the dev server via `npm run dev`.
2. Build the project with `npm run generate` and run a `http-server` from within `dist`.
3. Serve `dist` from nginx running inside a Docker container. I can paste here the Dockerfile should you want to try on your end. This means that the default nginx configs should serve the app as expected.

**Comment by andresgz** [comment]
Thanks @caroso1222 I updated the nginx config to resolve it, there was something wrong there
